### ISSUE TITLE
Make auth_user() function

### ISSUE THREAD

**Issue by eternalklaus** [KAIST-IS521/2018s-onion-team1#13]
Make auth_user() function. 

You can access the code at url: 
https://github.com/KAIST-IS521/2018s-onion-team1/blob/master/src/key_manager.c.

It authorize user. 
- Input : user's githubID
- output : 0 or 1. 

ex) if you input "hansh17" to this function......
     If this machine is hansh17's machine : return 1
     If this machine is eternalklaus's machine : return 0.

**Comment by Dauren2495** [comment]
Can you check out my branch? I implemented user_auth there.

**Comment by eternalklaus** [comment]
I checked and merged it. 
Thanks!
Issue closed.
