### ISSUE TITLE
Make Module : isClientAlive

### ISSUE THREAD

**Issue by eternalklaus** [KAIST-IS521/2018s-onion-team1#16]
Dauren, 

Our dbserver check client regularly 
whether client is alive or not.

So we need function like below. 

int isClientAlive(IP, Port){ 
 // if IP:Port is opened and accessable, return 1
 // else, (IP:Port is now closed) return 0 
}

I'll use use this on dbserver_server.c
would you please make this module?

**Comment by eternalklaus** [comment]
Here is prototype of function. 
line 20. 

`https://github.com/KAIST-IS521/2018s-onion-team1/blob/jiwon/src/dbserver_server.c`

**Comment by MincheolSon** [comment]
What is the latest version of server.c file for server and client?

**Comment by MincheolSon** [comment]
I make a draft for that function on my branch (mincheol), dbserver_server.c

**Comment by eternalklaus** [comment]
Thank you @MincheolSon 
Issue closed.
