### ISSUE TITLE
Make Module : PGP passphrase auth function

### ISSUE THREAD

**Issue by eternalklaus** [KAIST-IS521/2018s-onion-team1#19]
We need function whether user typed `passphrase` correctly or not. 

This function check 
whether `PGP_passphrase` string is match with PGP private key(which is already registered in the machine) or not. 

```
int  auth_passphrase(char *PGP_passphrase, char *mygithubId){
	// if correct, return 1;
	// else, return 0;
}
```

Here is prototype. 
https://github.com/KAIST-IS521/2018s-onion-team1/blob/jiwon/src/key_manager.c

**Comment by eternalklaus** [comment]
만약 유저가 입력한 PGP_passphrase 가  등록된 private key의 passphrase 와 일치한다면 1을 리턴합니다. 
만약 유저가 passphrase 를 잘못입력했다면 0을 리턴합니다.

**Comment by Dauren2495** [comment]
I am very sorry for lateness I implemented this function in my branch

**Comment by MincheolSon** [comment]
Is this closed issue?

**Comment by eternalklaus** [comment]
Yes I confirmed. It works well~
Thank you for your efforts.

Issue closed.
