### ISSUE TITLE
Comments from TA

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2018s-onion-team1#21]
Hi everyone.

Looks like you all work hard from last week and some incredible thing is gonna made. I expect it :)

Anyway, I have some comments for you.

 - Write up all the documents in English, especially [README.md](https://github.com/KAIST-IS521/2018s-onion-team1/blob/master/README.md). You all know one of our team member is not fluent in Korean so share all of your process to him.

 - As the professor said #8,  I saw the Issues are only organized by team leader, not team members. In other words, except team leader, team members do not comment or leave a issue on Github. Then, TA and Prof do not see any activity from each one. I know that all of you have done some commit to your own  repository but  no issue can be seen. This project is not easy task and have a lot of interactive things to do so try to leave all of your traces to Github.

Seems that lots of modules are still being made, so keep working hard.

Close the this issue whenever you get it.

Thanks

**Comment by hansh17** [comment]
I confirmed it

**Comment by eternalklaus** [comment]
I also confirmed it. Thank you for the comment.
