### ISSUE TITLE
Checkpoint comment

### ISSUE THREAD

**Issue by sangkilc** [KAIST-IS521/2018s-onion-team1#23]
1. It seems that only two students are working on the project. Especially I want to see more contributions from @MincheolSon  and @Dauren2495.

2. No working prototype so far. You should make a working (not necessarily complete) prototype ASAP.

3. I expect to see more active discussions. Especially I expect you guys to make use of PRs so that everyone can have discussion on important changes.

4. Why are you using Hangul comments when there is a foreign student? Maybe @Dauren2495 speaks well in Korean?

**Comment by sangkilc** [comment]
TA @oxsignal  will give you some more comments

**Comment by oxsignal** [comment]
@sangkilc I already open the issue  similar with you, closed yesterday.  Thank you  :)

**Comment by sangkilc** [comment]
- The figure in the README seems like not yours. You should give a citation.
- What is your product's name?
- I want to see passion from every member in this team about your product. Hope to see an exciting presentation.

**Comment by hansh17** [comment]
I confirmed it. All of our team member will follow professor's and TA's advice.

I have some question about 4th comment. Should we use English on issue when one-to-one communication takes place?

**Comment by sangkilc** [comment]
So I guess the question here is that if you have created an issue in Github, and resolved it offline, should you leave a comment or not. Right?

I think it is a good practice to leave a short message what happened in the offline meeting even if all the members have discussed the issue.

Now, what if the issue is resolved by having a offline meeting with a subset of the members? Then of course, you should share your design decision with other members. And in your case, since you have a foreign student, you should use English for this matter.

**Comment by eternalklaus** [comment]
Thank you for the comment .

- We edited README.md in english, and also added citation on figure. 
- We uploaded working prototype  at `https://github.com/KAIST-IS521/2018s-onion-team1/tree/master/src`. 

We'll proceed with your comments considered. 
Thank you.
