### ISSUE TITLE
Messenger name candidates

### ISSUE THREAD

**Issue by hansh17** [KAIST-IS521/2018s-onion-team1#25]
- Cryptalk (크립톡)
- Enctalk (잉크톡)

If anyone has any ideas, upload here

**Comment by eternalklaus** [comment]
DVMA (Damn Vulnerable Messenger Application)..?  haha just kidding...

- Safetalk
- Onioni

**Comment by hansh17** [comment]
any other things? 
vote on Saturday or Sunday?

**Comment by eternalklaus** [comment]
@Dauren2495  @MincheolSon  Do you have any other idea?

**Comment by MincheolSon** [comment]
- SOT (Safe Onion Talk)

**Comment by eternalklaus** [comment]
I think cryptalk is a good idea.

**Comment by hansh17** [comment]
I think so too.. I already use that name in several slides..; How about @Dauren2495 @MincheolSon

**Comment by hansh17** [comment]
Oh there already exists named Cryptalk. We should change our product name. We can choose safetalk, enctalk, onioni, SOT

**Comment by hansh17** [comment]
how about safetalk?

**Comment by eternalklaus** [comment]
We decided our product name `safetalk`
Thank you for the idea.
Issue closed.
