### ISSUE TITLE
[Bug] NULL parameter mis-handling in dv_send() 

### ISSUE THREAD

**Issue by eternalklaus** [KAIST-IS521/2018s-onion-team1#32]
Steps
1.  run dvonion 
2.  inside the dvonion's command window, type this command.
`/sendmsg` or `/sendmsg user1`
  
Result
1. Segmentation fault
   
Reason
1. Maybe.. in case of parameter of `/sendmsg` is null,  unintentional memory reference happens... 

I'm planning to add exception handler to manage this.

**Comment by hansh17** [comment]
I checked it. I report some bug @eternalklaus

**Comment by eternalklaus** [comment]
Bug fixed. Issue closed.
