### ISSUE TITLE
[Bug] Segmentation fault when running dvonion

### ISSUE THREAD

**Issue by hansh17** [KAIST-IS521/2018s-onion-team1#34]
Steps

- run dvonion
- type id of user 1 / password of user1
- ask something (y/N) -> choose yes

Result

    Segmentation fault

Reason

    I don't know exactly..

**Comment by hansh17** [comment]
Umm I think it happened because I execute files on root account (not user1 account). I'll try again

**Comment by eternalklaus** [comment]
`Segmentation fault` occurs whenever you login using root account?
Or if you fixed.. can I close this issue?

**Comment by hansh17** [comment]
Yes you can close it @eternalklaus
