### ISSUE TITLE
[Presentation] Write a review about our product

### ISSUE THREAD

**Issue by hansh17** [KAIST-IS521/2018s-onion-team1#35]
For presentation, I will make a slide about product review.

So please write a review about it

**Comment by hansh17** [comment]
It is quite a good product. I was reluctant to use messenger because of surveillance by government, but I am not worried about that from using this product. Anonymity is guaranteed during communication, and no one can see the contents. I can feel free to chat. However, it is still in the early stages of the release, so user interface is inconvenient and the registration process is a bit tricky. I hope to these problems will be solved. (3.0 / 5.0)

**Comment by MincheolSon** [comment]
This is good product to secrete my messages and files. If you want to communicate with security and anonymity, i recommend this product. However, i have a concern that its interface is a little inconvenient. Although inconvenient, this is certainly necessary messenger if you consider your security.
(3.8 / 5.0)
