### ISSUE TITLE
Detailed protocol features in README.md

### ISSUE THREAD

**Issue by eternalklaus** [KAIST-IS521/2018s-onion-team1#36]
Would you please add detailed protocol features in README.md?

Sender makes original data block depend on the `type(text/file)` of data. 
See below.

- in the case of `File`
| line No. | Description      |
|----------|-----------------|
| line 1   | "final"                |
| line 2   | "File"                 |
| line 3   | [Sender name]  |
| line 4   | [File Name]       |
| line 5   | [Message Block]|

- in the case of `Text`
| line No. | Description      |
|----------|-----------------|
| line 1   | "final"                |
| line 2   | "text"                 |
| line 3   | [Sender name]  |
| line 4   | NULL                 |
| line 5   | [Message Block]|

**Comment by hansh17** [comment]
OK I'll update it

**Comment by eternalklaus** [comment]
Thank you for your efforts @hansh17 
Issue closed.
