### ISSUE TITLE
[Bug] Segmentation Fault

### ISSUE THREAD

**Issue by Dauren2495** [KAIST-IS521/2018s-onion-team1#37]
I pulled Jiwon's branch to my working directory and compiled the code. However when I run ./dvonion I got Segmentation Fault, so as _Mincheol_ suggested I changed the value of g_ip to "127.0.0.1" in _dvonion.c_ , but I still get Segmentation Fault. Can you help me to resolve this problem?

**Comment by eternalklaus** [comment]
Hmm.. Did you followed the steps in here?
https://github.com/KAIST-IS521/2018s-onion-team1/tree/jiwon/src

**Comment by Dauren2495** [comment]
I think my problem was that I didn't copy .gnupg directory into my user directories. Now it works fine but my user window is little bit weird, I can't see what I am typing. Did you have such problem?
![screenshot from 2018-04-01 12-35-06](https://user-images.githubusercontent.com/25632371/38169590-22f5b064-35a9-11e8-8290-cc834f54369d.png)

**Comment by eternalklaus** [comment]
The reason of issue this : 
Three boxes of `dvonion` runs simultaneously runs as each thread.
Sometimes some boxes doesn't appear because of thread lock. 

Solution:
Try press [Enter].
Just pressing [Enter] can resolve the thread lock, and then maybe you can see all boxes in window.

**Comment by Dauren2495** [comment]
I think there some error with my screen. I changed window parameters RECV_H and LIST_H from 25 to 15 and SEND_Y from 26 to 20. Now it works properly.
