### ISSUE TITLE
About your repository management

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2018s-onion-team1#44]
![image](https://user-images.githubusercontent.com/22743966/38304983-321c187c-3846-11e8-98c5-27bb77d25286.png)

Recently, I expect your final works are merged in the master branch.

However, as the git log of your repository shows, I am very confused about what branch is the newest version (i.e., the complete code) of your project.

Please merge all of your team's work to the master branch before starting your next projects.

**Comment by eternalklaus** [comment]
I'll follow what you said. 
Thanks for comment.
