### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by sunnyeo** [KAIST-IS521/2018s-onion-team1#47]
When I run your program, there are some bugs look like following pictures.
In this case, i can't do anything.
![image](https://user-images.githubusercontent.com/36834930/38477211-72926114-3bec-11e8-94ee-a64c9ad5e9e4.png)
![peek 2018-04-09 12-05](https://user-images.githubusercontent.com/36834930/38477582-656e28d6-3bee-11e8-8c34-166126ced09d.gif)

**Comment by eternalklaus** [comment]
Thank you for comment!
We carefully checked your bug, and we found this bug happens under below condition. 
```
As user execute program many times in same shell, UI becomes weird like `pic.1`.
```

Unfortunately, we found it is because of memory management issue in `NCURSES library` itself.
There is one recommendation to avoid this issue. 
```
When this bug happens again, open a new shell and execute our program in a new shell.
Then this bug would not happened. 
```

We feel sorry we can't patch this bug. :(
